name: Bookstore Build & Deployment
on:
  push:
    branches: [ main, ops/deployment-pipeline ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: "16.x"
      - name: Install vite globally
        run: npm install --global vite
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      # upload artifacts
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: bookstore-artifact
          path: |
            ./
            Dockerfile
            package.json
          retention-days: 1

  push_docker:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      # download artifacts
      - name: Download artifact from Build
        uses: actions/download-artifact@v3
        with:
          name: bookstore-artifact
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract version and set it to TAG env var
        run: |
          echo "TAG=$(jq -r '.version' package.json)" >> $GITHUB_ENV
      - name: Build Docker image
        run: |
            docker build -t bookstore_v${{ env.TAG }} .
            docker tag bookstore_v${{ env.TAG }} ${{ secrets.DOCKER_USER }}/octo:bookstore_v${{ env.TAG }}
      - name: Upload Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/octo:bookstore_v${{ env.TAG }}