name: Bookstore Build & Deploy

# ---= Build =---
# 1. build frontend code via vite
# 2. create docker image for frontend code via dockerfile
# 3. publish docker image to private repo
# 4. define book website & api images in compose file

# ---= Deploy =---
# 1. provide manual option to deploy to QA or PROD
# 2. use shell commands or script to ssh to selected server
# 3. copy over the compose file and startup containers

on:
  push:
    branches:
      - main
      - misc/pipeline-setup

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: "16.x"
      - name: Install vite globally
        run: npm install --global vite
      - name: Build app
        run: npm install |
             npm run build
      - name: Docker login
        env: 
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Docker image
        run: docker build -t bookstore:(cat package.json | jq -r '.version') .  
      - name: Upload Docker image to Docker Hub
        run: docker push ${{secrets.DOCKER_USER}}/abudev:bookstore

  # deploy:
    # name: Deploy
    # needs: build
    # runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'

    # steps:
    #   - name: Deploy to QA
    #     uses: actions/download-artifact@v3
    #     with:
    #       name: production-files
    #       path: ./dist

    #   - name: Deploy to Production
    #     environment: PROD
    #     steps:
    #       - uses: actions/checkout@v3
    #       - name: copy file via ssh password
    #         uses: appleboy/scp-action@v0.1.4
    #         with:
    #           host: ${{ secrets.HOST }}
    #           username: ${{ secrets.USERNAME }}
    #           password: ${{ secrets.PASSWORD }}
    #           port: ${{ secrets.PORT }}
    #           source: "docker/docker-compose.yml"
    #           target: /home/thor/apps/bookstore